version: '3'

services:
 spring:
   image: docker-spring
   build: movieCruiser/
   restart: always
   network_mode: "host"
   container_name: spring-docker
   depends_on:
     - mongo
   ports:
     - 8082:8082
   expose:
     - 8082



 mongo:
   image: mongo:latest
   ports:
     - "3306:3306"
   container_name: mongo-docker
   network_mode: host
